### ISSUE TITLE
Missing dependency babel-eslint

### ISSUE THREAD

**Issue by dotnetCarpenter** [eventualbuddha/rollup-starter-project#4]
I get the following error after `clone` and then `npm i 

````
npm i

> rollup-starter-project@1.0.0 prepublish C:\Users\dotnet\Projects\playground\rollup-starter-project
> npm run build && npm test


> rollup-starter-project@1.0.0 prebuild C:\Users\dotnet\Projects\playground\rollup-starter-project
> eslint lib test


C:\Users\dotnet\Projects\playground\rollup-starter-project\lib\index.js
  0:0  error  Cannot find module 'babel-eslint'
```

**Comment by dotnetCarpenter** [comment]
There is a lot similar named dependencies. Are they all in use?

**Comment by eventualbuddha** [comment]
If you mean the `babel-plugin` ones, then yes, they're all included by the `es2015-rollup` preset.

**Comment by dotnetCarpenter** [comment]
Just to clarify, can you check that this is correct?

```
"babel-eslint": "eslint for es6 - a plugin for babel",
"babel-preset-es2015-rollup": "all of the babel-preset-es2015 plugins but with support for rollup helpers",
"eslint": "eslint - is it needed when we have babel-eslint?",
"mocha": "test runner",
"rollup": "package builder",
"rollup-plugin-babel": "rollup package builder for es6 - a plugin to rollup",
"rollup-plugin-multi-entry": "support for merging several entry files - a plugin to rollup"
```

@eventualbuddha Is eslint really needed?

**Comment by dotnetCarpenter** [comment]
@eventualbuddha would be great to have this information in the readme, so newcomers like me easier can pick up why a dependency is needed. It took a while to figure out and is essential when using rollup in my own project.

**Comment by eventualbuddha** [comment]
@dotnetCarpenter I agree! Would be very helpful to submit a PR with that info. (And yes, it seems you do need both `eslint` and `babel-eslint` since the latter doesn't ship with a binary).

**Comment by eventualbuddha** [comment]
@dotnetCarpenter I just added a section to the [README](https://github.com/rollup/rollup-starter-project#dependencies) documenting the dependencies. Is that what you had in mind?

**Comment by dotnetCarpenter** [comment]
Yes but even better. Great explanation.
Am I understanding this correctly: rollup-plugin-babel is the removed ES2015 modules support from babel-preset-es2015? If that is the case, your explanation is better than my guesses.

**Comment by dotnetCarpenter** [comment]
Only one thing still confuses me. Why is the entry to rollup **rollup-plugin-multi-entry:entry-point** and not the combined test files `multiEntry('test/**/*_test.js')`?

Ahh. I see that you updated your plugin. Makes more sense now.

**Comment by eventualbuddha** [comment]
`rollup-plugin-babel` simply runs babel using the configuration you give it (or babel reads from a `.babelrc` file). It checks to make sure a module transform doesn't happen, but how you configure that is up to you. The default way is to simply use the `babel-preset-es2015-rollup` preset which removes ES2015 module support from `babel-preset-es2015`.

As for the entry point thing, `rollup-plugin-multi-entry:entry-point` is the internal module id that the plugin should load with imports for all the matching files. You shouldn't have to care.
